server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres #${POSTGRES_URL}
    username: root #${POSTGRES_USER}
    password: password #${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop #${POSTGRES_DDLAUTO}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  rabbitmq:
    addressUrl: 'http://localhost:15672' #${RABBITMQ_ADDRESSURL}
    queue: email #${RABBITMQ_QUEUE}